app            = "zenith-link"
primary_region = "jnb"

[build]
  dockerfile = "docker/Dockerfile.fly"

[env]
  GROUNDSTATION_ADDR = ":8080"
  SPACECRAFT_SCID    = "90"
  SPACECRAFT_VCID    = "0"
  SPACECRAFT_APID    = "256"
  RELAY_SCID         = "91"
  RELAY2_SCID        = "92"
  GS_LAT             = "-1.2864"
  GS_LON             = "36.8172"
  MIN_ELEV_DEG       = "5.0"
  POLL_INTERVAL_SEC  = "30"
  STATIC_DIR         = "/app/dist"

[http_service]
  internal_port        = 8080
  force_https          = true
  auto_stop_machines   = "off"
  auto_start_machines  = true
  min_machines_running = 1

  [http_service.concurrency]
    type       = "connections"
    hard_limit = 100
    soft_limit = 80

[[vm]]
  size = "shared-cpu-2x"
