FROM golang:1.22-alpine AS builder
WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -trimpath -ldflags="-s -w" \
    -o /bin/relay ./cmd/relay

FROM scratch
COPY --from=builder /bin/relay /relay
EXPOSE 8082
ENTRYPOINT ["/relay"]
