FROM golang:1.22-alpine AS builder
WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -trimpath -ldflags="-s -w" \
    -o /bin/relay2 ./cmd/relay2

FROM scratch
COPY --from=builder /bin/relay2 /relay2
EXPOSE 8083
ENTRYPOINT ["/relay2"]
