FROM golang:1.22-alpine AS builder
WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -trimpath -ldflags="-s -w" \
    -o /bin/spacecraft ./cmd/spacecraft

FROM scratch
COPY --from=builder /bin/spacecraft /spacecraft
EXPOSE 8080
ENTRYPOINT ["/spacecraft"]
