upstream groundstation { server groundstation:8081; }
upstream spacecraft    { server spacecraft:8080;    }
upstream relay1        { server relay:8082;         }
upstream relay2        { server relay2:8083;        }

map $http_upgrade $connection_upgrade {
    default upgrade;
    ''      close;
}

server {
    listen 80;
    server_name orbitron-dev.ddns.net;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name orbitron-dev.ddns.net;

    ssl_certificate     /etc/letsencrypt/live/orbitron-dev.ddns.net/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/orbitron-dev.ddns.net/privkey.pem;
    ssl_protocols       TLSv1.2 TLSv1.3;
    ssl_ciphers         ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305;
    ssl_prefer_server_ciphers off;
    ssl_session_cache   shared:SSL:10m;
    ssl_session_timeout 1d;

    proxy_buffer_size       128k;
    proxy_buffers           4 256k;
    proxy_busy_buffers_size 256k;

    location /ws {
        proxy_pass         http://groundstation;
        proxy_http_version 1.1;
        proxy_set_header   Upgrade    $http_upgrade;
        proxy_set_header   Connection $connection_upgrade;
        proxy_set_header   Host       $host;
        proxy_read_timeout 3600s;
    }

    location ~ ^/(health|latest|receive|metrics|command|capabilities|topology) {
        proxy_pass http://groundstation;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location ~ ^/(windows|state|track|constellation|tle|events|payload|inference) {
        proxy_pass http://spacecraft;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /relay/ {
        rewrite    ^/relay/(.*)$ /$1 break;
        proxy_pass http://relay1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /relay2/ {
        rewrite    ^/relay2/(.*)$ /$1 break;
        proxy_pass http://relay2;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location / {
        root  /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }
}
